name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions: # Adicionado para garantir permissões de escrita
      contents: write
    steps:
      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: GhabryelHenrique
          # Gera a animação e salva em dist/github-contribution-grid-snake.svg
          # e também uma versão com o fundo escuro em dist/github-contribution-grid-snake-dark.svg
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Você pode adicionar uma versão para o tema escuro se quiser
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg

      # Faz o deploy do arquivo gerado para a branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
